package importer

import (
	"strconv"
	"testing"

	"github.com/xuri/excelize/v2"
)

// exportRow mirrors one row written by writeMonthSheet
// (backend/internal/httpapi/export_handlers.go). The layout is duplicated here
// on purpose: this package cannot import httpapi (httpapi imports it), and the
// integration test that drives the real writer needs a database. Keep the two
// in step — a drift here is a silently unreadable export.
type exportRow []any

func writeSheet(t *testing.T, name string, rows []exportRow) string {
	t.Helper()
	f := excelize.NewFile()
	defer f.Close()
	f.SetSheetName("Sheet1", name)
	for i, row := range rows {
		for j, v := range row {
			col, _ := excelize.ColumnNumberToName(j + 1)
			if err := f.SetCellValue(name, col+strconv.Itoa(i+1), v); err != nil {
				t.Fatalf("set cell: %v", err)
			}
		}
	}
	path := t.TempDir() + "/export.xlsx"
	if err := f.SaveAs(path); err != nil {
		t.Fatalf("save fixture: %v", err)
	}
	return path
}

// exportFixture is a full month sheet in the app's own export layout, built to
// contain exactly the things that used to be lost on reimport: a carryover
// income entry, an itemized income source with line items, a category whose
// name starts with "Totaal", a transaction with no date, a zero-amount line and
// a negative (refund) transaction.
func exportFixture() []exportRow {
	return []exportRow{
		{"Juli 2026"},
		{},
		{"Inkomsten"},
		{"Bron", "Bedrag"},
		{"Salaris", 2500.0},
		{"Freelance", 450.0},             // itemized: line items below
		{"Doorlopen maand Juni", 123.45}, // generated by close, must not reimport
		{"Totaal inkomsten", 3073.45},
		{},
		{"Uitgaven"},
		{"Categorie", "Bedrag", "Type"},
		{"Boodschappen", 370.0, "Boekingen"},
		{"Totaal onderhoud", 150.0, "Vast"}, // name starts with "Totaal"
		{"'-Onderhoud", 0.0, "Vast"},        // formula-guard apostrophe from the export
		{"Huur", 1000.0, "Vast"},
		{"Vakantiepot", 0.0, "Vast"},
		{"Totaal uitgaven", 1520.0},
		{},
		{"Surplus", 1553.45},
		{},
		{"Transacties"},
		{"Datum", "Categorie", "Omschrijving", "Bedrag"},
		{"2026-07-03", "Boodschappen", "AH", 250.0},
		{"", "Boodschappen", "Onbekende datum", 170.0}, // tx_date is nullable
		{"2026-07-10", "Boodschappen", "Retour", -50.0},
		{},
		{"Inkomsten transacties"},
		{"Datum", "Bron", "Omschrijving", "Bedrag"},
		{"2026-07-05", "Freelance", "Klus A", 300.0},
		{"", "Freelance", "Klus B", 150.0},
	}
}

func TestDetectAndParseExportFormatRoundTrip(t *testing.T) {
	path := writeSheet(t, "2026-07", exportFixture())

	sheets, skipped, err := DetectAndParse(path)
	if err != nil {
		t.Fatalf("DetectAndParse: %v", err)
	}
	if len(skipped) != 0 {
		t.Errorf("skipped: want none, got %v", skipped)
	}
	if len(sheets) != 2 {
		t.Fatalf("sheets: want 2 (Overview+Details), got %d", len(sheets))
	}

	var ov, det *SheetData
	for i := range sheets {
		if sheets[i].Kind == "Overview" {
			ov = &sheets[i]
		} else {
			det = &sheets[i]
		}
	}
	if ov == nil || det == nil {
		t.Fatal("expected one Overview and one Details sheet")
	}
	if ov.Year != 2026 || ov.Month != 7 {
		t.Errorf("period: want 2026-07, got %d-%02d", ov.Year, ov.Month)
	}
	if len(ov.Problems) != 0 {
		t.Errorf("problems: want none, got %v", ov.Problems)
	}

	// ── Income: the carryover row must not come back as ordinary income ──
	if len(ov.Incomes) != 2 {
		t.Fatalf("incomes: want 2 (carryover excluded), got %+v", ov.Incomes)
	}
	wantIncome := map[string]int64{"Salaris": 250000, "Freelance": 45000}
	var incomeTotal int64
	for _, inc := range ov.Incomes {
		want, ok := wantIncome[inc.Label]
		if !ok {
			t.Errorf("unexpected income row %q", inc.Label)
			continue
		}
		if inc.AmountCents != want {
			t.Errorf("income %q: want %d, got %d", inc.Label, want, inc.AmountCents)
		}
		incomeTotal += inc.AmountCents
	}
	if incomeTotal != 295000 {
		t.Errorf("income total: want 295000, got %d", incomeTotal)
	}

	// ── Expenses: "Totaal onderhoud" must not terminate the section, and a
	//    €0 placeholder line must survive ──
	if len(ov.Lines) != 5 {
		t.Fatalf("budget lines: want 5, got %+v", ov.Lines)
	}
	wantLines := map[string]int64{"Boodschappen": 37000, "Totaal onderhoud": 15000, "Huur": 100000, "Vakantiepot": 0, "-Onderhoud": 0}
	var expenseTotal int64
	for _, bl := range ov.Lines {
		want, ok := wantLines[bl.Label]
		if !ok {
			t.Errorf("unexpected budget line %q", bl.Label)
			continue
		}
		if bl.AmountCents != want {
			t.Errorf("budget line %q: want %d, got %d", bl.Label, want, bl.AmountCents)
		}
		expenseTotal += bl.AmountCents
	}
	if expenseTotal != 152000 {
		t.Errorf("expense total: want 152000, got %d", expenseTotal)
	}

	// ── Transactions: dateless and negative rows both survive ──
	if len(det.Txs) != 3 {
		t.Fatalf("transactions: want 3, got %+v", det.Txs)
	}
	var txTotal int64
	var sawEmptyDate, sawNegative bool
	for _, tx := range det.Txs {
		txTotal += tx.AmountCents
		if tx.Date == "" {
			sawEmptyDate = true
		}
		if tx.AmountCents < 0 {
			sawNegative = true
		}
	}
	if !sawEmptyDate {
		t.Error("transaction with an empty Datum cell was dropped")
	}
	if !sawNegative {
		t.Error("negative (refund) transaction was dropped")
	}
	if txTotal != 37000 {
		t.Errorf("transaction total: want 37000 (= Boodschappen budget line), got %d", txTotal)
	}

	// ── Itemized income line items ──
	if len(det.IncomeTxs) != 2 {
		t.Fatalf("income transactions: want 2, got %+v", det.IncomeTxs)
	}
	var itxTotal int64
	for _, itx := range det.IncomeTxs {
		if itx.SourceLabel != "Freelance" {
			t.Errorf("income transaction source: want Freelance, got %q", itx.SourceLabel)
		}
		itxTotal += itx.AmountCents
	}
	if itxTotal != 45000 {
		t.Errorf("income transaction total: want 45000 (= Freelance income row), got %d", itxTotal)
	}
}

// TestParseExportSheetReportsBadAmounts covers the cells that used to be
// silently turned into 0 (and, for the huge one, into a value that made the
// whole month unloadable).
func TestParseExportSheetReportsBadAmounts(t *testing.T) {
	rows := []exportRow{
		{"Inkomsten"},
		{"Bron", "Bedrag"},
		{"Salaris", "1e300"},
		{"Bonus", "n.v.t."},
		{"Totaal inkomsten", 0},
		{},
		{"Transacties"},
		{"Datum", "Categorie", "Omschrijving", "Bedrag"},
		{"2026-07-03", "Boodschappen", "AH", "€ 1.234,56"},
	}
	path := writeSheet(t, "2026-07", rows)

	sheets, _, err := DetectAndParse(path)
	if err != nil {
		t.Fatalf("DetectAndParse: %v", err)
	}
	var ov, det *SheetData
	for i := range sheets {
		if sheets[i].Kind == "Overview" {
			ov = &sheets[i]
		} else {
			det = &sheets[i]
		}
	}
	if len(ov.Incomes) != 0 {
		t.Errorf("unreadable income rows must not be imported, got %+v", ov.Incomes)
	}
	if len(ov.Problems) != 2 {
		t.Errorf("problems: want 2 (one per bad cell), got %v", ov.Problems)
	}
	if len(det.Txs) != 1 || det.Txs[0].AmountCents != 123456 {
		t.Errorf("currency-formatted transaction: want 123456 cents, got %+v", det.Txs)
	}
}

func TestDetectAndParseRejectsUnknownWorkbook(t *testing.T) {
	path := writeSheet(t, "Notities", []exportRow{{"iets anders"}})
	if _, _, err := DetectAndParse(path); err == nil {
		t.Fatal("want an error for a workbook with no recognizable sheet names")
	}
}
