{{- if .Values.avatarStorage.filesystem.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-avatars
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.avatarStorage.filesystem.storageClassName }}
  storageClassName: {{ .Values.avatarStorage.filesystem.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.avatarStorage.filesystem.size }}
{{- end }}
