{{- if and .Values.postgres.cnpg.enabled .Values.postgres.cnpg.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.postgres.cnpg.clusterName }}-backup
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-pg
spec:
  schedule: {{ .Values.postgres.cnpg.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.postgres.cnpg.clusterName }}
{{- end }}
