apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.clusterName }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-pg
spec:
  instances: {{ .Values.postgres.instances }}
  imageName: {{ .Values.postgres.imageName }}
  storage:
    size: {{ .Values.postgres.storageSize }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.databaseName }}
      owner: {{ .Values.postgres.ownerName }}
{{- if .Values.postgres.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.postgres.backup.retentionPolicy | quote }}
    barmanObjectStore:
      destinationPath: {{ .Values.postgres.backup.destinationPath | quote }}
      {{- if .Values.postgres.backup.endpointURL }}
      endpointURL: {{ .Values.postgres.backup.endpointURL | quote }}
      {{- end }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.postgres.backup.existingSecret }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.postgres.backup.existingSecret }}
          key: ACCESS_SECRET_KEY
{{- end }}
